### ISSUE TITLE
Missing nixos-generator formats

### ISSUE THREAD

**Issue by LovingMelody** [snowfallorg/lib#65] opened 2024-03-16 15:46 UTC
Noticed that not all nixos-generator formats are supported, for example `sd-aarch64-installer` is not supported  (no output defined), unsure if any other formats are having issues.

**Comment by jakehamilton** [comment] 2024-03-16 21:42
It can be a bit awkward for some nixos-generators outputs since they mention a system type, but for Snowfall Lib to pick up your system it will need to start with an architecture. Can you try specifying `aarch64-sd-aarch64-installer`?

**Comment by LovingMelody** [comment] 2024-03-17 00:24
```console
melody in DotFiles on  main [$⇡] took 4s
at 20:23:23 ❯ ls --tree systems/aarch64-sd-aarch64-installer
 aarch64-sd-aarch64-installer
└──  installer
    └──  default.nix
melody in DotFiles on  main [$⇡]
at 20:23:29 ❯ nix eval .\#

.\#aesthetic-wallpapers       .\#homeModules                .\#quint
.\#catppuccin-base16          .\#install-isoConfigurations  .\#rename-padded-numbers
.\#checks                     .\#lib                        .\#reshade
.\#darwinConfigurations       .\#linux-wallpaperengine      .\#reshade-steam-proton
.\#darwinModules              .\#nixosConfigurations        .\#robotnixConfigurations
.\#devShells                  .\#nixosModules               .\#_snowfall
.\#formatter                  .\#obs-composite-blur         .\#spacedrive
.\#gposingway                 .\#overlays                   .\#templates
.\#home                       .\#packages
.\#homeConfigurations         .\#pkgs
```
Still nothing

**Comment by jakehamilton** [comment] 2024-03-17 01:23
@LovingMelody can you share your flake in a GitHub repo?

**Comment by LovingMelody** [comment] 2024-03-17 13:18
https://gitlab.com/LovingMelody/configsreborn

**Comment by jakehamilton** [comment] 2024-05-23 00:24
After digging into this I can confirm that this is an issue only in your repository. In fact, renaming the directory `installer` to `my-installer` makes it work. My best guess here is that you may have originally named one of the directories or files using different casing while on macOS and attempted to change it later. That may be wrong, but other than that I'm not quite sure I have any idea why this would be happening. It isn't the name of the system, I can create one named `installer` using the same structure in my flake without issue.

As of now I don't believe this is related to Snowfall Lib so I am going to close this issue.

**Closed by jakehamilton** 2024-05-23 00:24 UTC
