### ISSUE TITLE
How can I debug a snowfall config?

### ISSUE THREAD

**Issue by tqwewe** [snowfallorg/lib#4] opened 2023-02-20 05:42 UTC
I've created my own config, but sometimes my modules don't seem to be loaded since traces don't print, and the variables are not set in the nix repl.

When running `sudo nixos-rebuild build --flake ~/config` I get no errors, but when running `nix flake check ~/config`, I always get an error:
```
~/config main• [1] nix flake check . --no-build --show-trace
warning: Git tree '/home/ari/config' is dirty
warning: unknown flake output 'package-namespace'
error: module must be a function or an attribute set

       … while checking the NixOS module 'nixosModules.home'
```
And `/modules/home/default.nix` contains:
```nix
{ config, pkgs, ... }:
{
  config = {
    home-manager = {
      useUserPackages = true;

      users.ari = {
        home.stateVersion = config.system.stateVersion;
      };
    };
  };
}
```

When creating a brand new project using the template, flake check also seems to fail there:
```bash
$ mkdir /tmp/nixconf && cd /tmp/nixconf

$ nix flake init -t github:snowfallorg/templates#system
wrote: /tmp/nixconf/systems/x86_64-linux/example/hardware.nix
wrote: /tmp/nixconf/systems/x86_64-linux/example/default.nix
wrote: /tmp/nixconf/systems/x86_64-linux/example
wrote: /tmp/nixconf/systems/x86_64-linux
wrote: /tmp/nixconf/systems
wrote: /tmp/nixconf/flake.nix
wrote: /tmp/nixconf/modules/snowfall/default.nix
wrote: /tmp/nixconf/modules/snowfall
wrote: /tmp/nixconf/modules

$ nix flake check . --show-trace
warning: unknown flake output 'lib'
error: module must be a function or an attribute set

       … while checking the NixOS module 'nixosModules.snowfall'

$ cat ./modules/snowfall/default.nix
{ lib, config, ... }:

let
  cfg = config.snowfall.example;
in
{
  options.snowfall.example = {
    enable = lib.mkEnableOption "Snowfall Example";
  };

  config = lib.mkIf cfg.enable {
    environment.variables = {
      SNOWFALL_EXAMPLE = "enabled";
    };
  };
}
```

At this point I seem to have no way of knowing what might actually be going wrong since nixos-rebuild succeeds, but nix flake check always fails.

**Comment by jakehamilton** [comment] 2023-02-20 09:35
It looks like this is a duplicate of #2. See this reply for details: https://github.com/snowfallorg/lib/issues/2#issuecomment-1435524230

**Closed by jakehamilton** 2023-02-20 09:35 UTC
